Zuilding.Web/Controllers/AuthenticationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Zuilding.Web.Models;
using Zuilding.Web.Domain;
using Microsoft.AspNet.Identity;
using MongoDB.AspNet.Identity;
using Microsoft.Owin.Security;
using Zuilding.Web.Repository;

namespace Zuilding.Web.Controllers
{
    // [Authorize]
    public class AuthenticationController : Controller
    {
        //
        // POST: /Account/Login
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginModel model)//, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                //WebSecurity.Login(model.UserName, model.Password, persistCookie: model.RememberMe);
                var manager = new UserManager<Account>(new UserStore<Account>("mongodb://localhost/authentication"));
                 var account = manager.Find(model.UserName, model.Password);

                if (account != null)
                {
                    var authenticationManager = HttpContext.GetOwinContext().Authentication;
                    var userIdentity = manager.CreateIdentity(account, DefaultAuthenticationTypes.ApplicationCookie);
                    authenticationManager.SignIn(new AuthenticationProperties() { }, userIdentity);
                }
            }

            return RedirectToLocal("");
            //{
            //    return RedirectToLocal(returnUrl);
            //}

            //// If we got this far, something failed, redisplay form
            //ModelState.AddModelError("", "The user name or password provided is incorrect.");
            //return View(model);
        }

        //
        // POST: /Account/LogOff
        [HttpGet]
        public ActionResult LogOff()
        {
            var authenticationManager = HttpContext.GetOwinContext().Authentication;
            authenticationManager.SignOut();

            return RedirectToLocal("");
        }

        #region dontneedit
        ////
        //// GET: /Account/Register

        //[AllowAnonymous]
        //public ActionResult Register()
        //{
        //    return View();
        //}


        [HttpGet]
        public ActionResult Register()
        {
            return View("~/Views/register.cshtml");
        }

        ////
        //// POST: /Account/Register

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Register(RegisterModel model)
        {
            if (ModelState.IsValid)
            {
                // create builder
                var repo = AccountsRepository.FactoryCreate(new string[] { "Builder" }) as BuilderRepository;
                repo.create(new Account { 
                    email = model.Email, 
                    UserName = model.UserName, 
                    tenantId = model.tenantName}, model.Password);

                // login user
                var manager = new UserManager<Account>(new UserStore<Account>("mongodb://localhost/authentication"));
                var account = manager.Find(model.UserName, model.Password);
                var authenticationManager = HttpContext.GetOwinContext().Authentication;
                var userIdentity = manager.CreateIdentity(account, DefaultAuthenticationTypes.ApplicationCookie);
                authenticationManager.SignIn(new AuthenticationProperties() { }, userIdentity);

                return RedirectToAction("Index", "Home");
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        ////
        //// POST: /Account/Disassociate

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Disassociate(string provider, string providerUserId)
        //{
        //    string ownerAccount = OAuthWebSecurity.GetUserName(provider, providerUserId);
        //    ManageMessageId? message = null;

        //    // Only disassociate the account if the currently logged in user is the owner
        //    if (ownerAccount == User.Identity.Name)
        //    {
        //        // Use a transaction to prevent the user from deleting their last login credential
        //        using (var scope = new TransactionScope(TransactionScopeOption.Required, new TransactionOptions { IsolationLevel = IsolationLevel.Serializable }))
        //        {
        //            bool hasLocalAccount = OAuthWebSecurity.HasLocalAccount(WebSecurity.GetUserId(User.Identity.Name));
        //            if (hasLocalAccount || OAuthWebSecurity.GetAccountsFromUserName(User.Identity.Name).Count > 1)
        //            {
        //                OAuthWebSecurity.DeleteAccount(provider, providerUserId);
        //                scope.Complete();
        //                message = ManageMessageId.RemoveLoginSuccess;
        //            }
        //        }
        //    }

        //    return RedirectToAction("Manage", new { Message = message });
        //}

        ////
        //// GET: /Account/Manage

        //public ActionResult Manage(ManageMessageId? message)
        //{
        //    ViewBag.StatusMessage =
        //        message == ManageMessageId.ChangePasswordSuccess ? "Your password has been changed."
        //        : message == ManageMessageId.SetPasswordSuccess ? "Your password has been set."
        //        : message == ManageMessageId.RemoveLoginSuccess ? "The external login was removed."
        //        : "";
        //    ViewBag.HasLocalPassword = OAuthWebSecurity.HasLocalAccount(WebSecurity.GetUserId(User.Identity.Name));
        //    ViewBag.ReturnUrl = Url.Action("Manage");
        //    return View();
        //}

        ////
        //// POST: /Account/Manage

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Manage(LocalPasswordModel model)
        //{
        //    bool hasLocalAccount = OAuthWebSecurity.HasLocalAccount(WebSecurity.GetUserId(User.Identity.Name));
        //    ViewBag.HasLocalPassword = hasLocalAccount;
        //    ViewBag.ReturnUrl = Url.Action("Manage");
        //    if (hasLocalAccount)
        //    {
        //        if (ModelState.IsValid)
        //        {
        //            // ChangePassword will throw an exception rather than return false in certain failure scenarios.
        //            bool changePasswordSucceeded;
        //            try
        //            {
        //                changePasswordSucceeded = WebSecurity.ChangePassword(User.Identity.Name, model.OldPassword, model.NewPassword);
        //            }
        //            catch (Exception)
        //            {
        //                changePasswordSucceeded = false;
        //            }

        //            if (changePasswordSucceeded)
        //            {
        //                return RedirectToAction("Manage", new { Message = ManageMessageId.ChangePasswordSuccess });
        //            }
        //            else
        //            {
        //                ModelState.AddModelError("", "The current password is incorrect or the new password is invalid.");
        //            }
        //        }
        //    }
        //    else
        //    {
        //        // User does not have a local password so remove any validation errors caused by a missing
        //        // OldPassword field
        //        ModelState state = ModelState["OldPassword"];
        //        if (state != null)
        //        {
        //            state.Errors.Clear();
        //        }

        //        if (ModelState.IsValid)
        //        {
        //            try
        //            {
        //                WebSecurity.CreateAccount(User.Identity.Name, model.NewPassword);
        //                return RedirectToAction("Manage", new { Message = ManageMessageId.SetPasswordSuccess });
        //            }
        //            catch (Exception e)
        //            {
        //                ModelState.AddModelError("", e);
        //            }
        //        }
        //    }

        //    // If we got this far, something failed, redisplay form
        //    return View(model);
        //}

        ////
        //// POST: /Account/ExternalLogin

        //[HttpPost]
        //[AllowAnonymous]
        //[ValidateAntiForgeryToken]
        //public ActionResult ExternalLogin(string provider, string returnUrl)
        //{
        //    return new ExternalLoginResult(provider, Url.Action("ExternalLoginCallback", new { ReturnUrl = returnUrl }));
        //}

        ////
        //// GET: /Account/ExternalLoginCallback

        //[AllowAnonymous]
        //public ActionResult ExternalLoginCallback(string returnUrl)
        //{
        //    AuthenticationResult result = OAuthWebSecurity.VerifyAuthentication(Url.Action("ExternalLoginCallback", new { ReturnUrl = returnUrl }));
        //    if (!result.IsSuccessful)
        //    {
        //        return RedirectToAction("ExternalLoginFailure");
        //    }

        //    if (OAuthWebSecurity.Login(result.Provider, result.ProviderUserId, createPersistentCookie: false))
        //    {
        //        return RedirectToLocal(returnUrl);
        //    }

        //    if (User.Identity.IsAuthenticated)
        //    {
        //        // If the current user is logged in add the new account
        //        OAuthWebSecurity.CreateOrUpdateAccount(result.Provider, result.ProviderUserId, User.Identity.Name);
        //        return RedirectToLocal(returnUrl);
        //    }
        //    else
        //    {
        //        // User is new, ask for their desired membership name
        //        string loginData = OAuthWebSecurity.SerializeProviderUserId(result.Provider, result.ProviderUserId);

Zuilding.Web/Views/_entityList.cshtml
<!-- item -->
<script id="el-template-view" type="text/html">
    <div data-bind="text: id"></div>
    <button data-bind="click: edit">Edit</button>
    <button data-bind="click: del">Delete</button>
</script>
<script id="el-template-edit" type="text/html">
    <div data-bind="text: id"></div>
    <button data-bind="click: cancel">Cancel</button>
    <button data-bind="click: save">Save</button>
</script>
<!-- list -->
<script id="el-template-list" type="text/html">
    <ol data-bind="foreach: queryItems">
        <li data-bind="template: {name: templateNames.current()}">
        </li>
    </ol>
</script>
<!-- header - list header contains add new button, etc. -->
<script id="el-template-header" type="text/html">
    <div>
        <div class="btn-toolbar" style="padding-top:10px;">
            <div class="btn-group pull-right">
                <button data-bind="visible: options.allowAdd, enable: !addingNewMode(), click: function(a) {a.addNew({})}" type="button" class="btn btn-default">Add New</button>
            </div>
        </div>
        <div data-bind="template: {name: templateNames.headerContents}"></div>
    </div>
</script>
<!-- header contents -->
<script id="el-template-header-contents" type="text/html">
</script>
<!-- page -->
<script id="el-template-page" type="text/html">
    <div class="panel panel-body">
        <div data-bind="template: {name: templateNames.header}">
        </div>

        <div data-bind="visible: !isLoading(), template: {name: templateNames.list}">
        </div>
    </div>
</script>

Zuilding.Web/Views/_layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Builtin360</title>

    <link rel="stylesheet" type="text/css" href="content/bootstrap/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="content/sidebar.css">
    <link rel="stylesheet" type="text/css" href="content/main.css" />
    <link rel="stylesheet" type="text/css" href="content/uploadStyles.css" />
    <link rel="stylesheet" type="text/css" href="content/tipsy.css" />
    @RenderSection("styles", false)
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body>
    @Html.Partial("~/Views/_entityList.cshtml")
    <div id="zg-menu">
        @Html.Partial("~/Views/_menu.cshtml")
    </div>
    <div id="zg-contents">
        @RenderBody()
    </div>
    <div id="push"></div>
    <!--footer-->
    <div id="zg-footer" class="credit">
        <div class="container">
            <p>&copy; @DateTime.Now.Year - Builtin360</p>
        </div>
    </div>

    <script type="text/javascript" src="~/scripts/jquery.media.js"></script>
    <script type="text/javascript" src="~/scripts/jquery-ui-1.11.1.js"></script>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type='text/javascript' src='~/scripts/knockout-3.2.0.debug.js'></script>
    <script type='text/javascript' src='~/scripts/knockout.mapping-latest.js'></script>
    <script type="text/javascript" src="~/scripts/knockout.validation.js"></script>
    <script type="text/javascript" src="~/scripts/knockout-sortable.js"></script>
    <script type="text/javascript" src="~/scripts/jquery.tipsy.js"></script>

    <script type="text/javascript" src="~/scripts/app/lib/service.js"></script>
    <script type="text/javascript" src="~/scripts/app/lib/entityList.js"></script>
    <script type="text/javascript" src="~/scripts/app/viewmodels/menu.js"></script>
    <script type="text/javascript" src="~/scripts/app/viewmodels/sidebar.js"></script>
    @RenderSection("scripts", false)
</body>
</html>

Zuilding.Web/Views/_menu.cshtml
<!--top navbar -->
<header data-bind="with: menu" class="navbar navbar-inverse navbar-static-top">
    <!-- logo -->
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a data-bind="click: function(){current('')}, css : {selected: current() == ''}" class="navbar-brand" href="">Home</a>
    </div>

    <!-- top menu -->
    <nav class="navbar-collapse collapse">
        <ul class="nav navbar-nav" data-bind="foreach: items">
            <li data-bind="css: {active: $parent.current() == $data}"><a data-bind="click: function(){$parent.goto($data.name)}, text: $data.name" href=""></a></li>
        </ul>

        <!-- login controls -->
        <ul class="nav navbar-nav navbar-right">
            <li data-bind="visible: isAuthenticated, css : {active: current() == 'Accounts'}"><a data-bind="click: function() {goto('Accounts')}" class="navbar-button" href="">Accounts</a></li>
            <li data-bind="visible: isAuthenticated"><a href="Authentication/LogOff" class="navbar-button">Sign out</a></li>
            <li data-bind="visible: !isAuthenticated()"><a href="Authentication/Login" class="navbar-button">Sign in</a></li>
        </ul>
    </nav>
</header>

Zuilding.Web/Views/builder.cshtml
@{
    Layout = "/Views/_layout.cshtml";
}

<!--
     Main content page for Builder
-->
<div data-bind="visible: menu.current() == ''">
    @Html.Partial("/views/builder/_home.cshtml")
</div>

@*<div data-bind="with: checklists, visible: menu.current().name == 'Checklists'">
    @Html.Partial("/views/checklist/_index.cshtml")
</div>*@
@*<div data-bind="with: portfolios, visible: menu.current().name == 'Portfolios'">
    @Html.Partial("/Views/builder/_portfolios.cshtml")
</div>*@
<div data-bind="with: proposals, visible: menu.current().name == 'Proposals'">
    @Html.Partial("/Views/proposal/_container.cshtml")  
</div>
@*<div data-bind="with: contacts, visible: menu.current().name == 'Contacts'">
    @Html.Partial("/Views/contact/_index.cshtml")
</div>*@
@*<div data-bind="with: files, visible: menu.current().name == 'Files'">
    @Html.Partial("/Views/file/_files.cshtml")
</div>*@
<div data-bind="with: accounts, visible: menu.current() == 'Accounts'">
    @Html.Partial("/Views/accounts/_accounts.cshtml")
</div>
<!-- Application Scripts -->
@section scripts {
<script type="text/javascript" src="~/scripts/fileDrag.js"></script>
<script type="text/javascript" src="~/scripts/app/viewmodels/proposal/container.js"></script>
<script type="text/javascript" src="~/scripts/app/viewmodels/proposal/page.js"></script>
<script type="text/javascript" src="~/scripts/app/viewmodels/proposal/spec.js"></script>
<script type="text/javascript" src="~/scripts/app/viewmodels/proposal/financials.js"></script>
<script type="text/javascript" src="~/scripts/app/viewmodels/proposal/cashFlow.js"></script>
<script type="text/javascript" src="~/scripts/app/viewmodels/proposal/customTab.js"></script>
<script type="text/javascript" src="~/scripts/app/viewmodels/checklist.js"></script>
<script type="text/javascript" src="~/scripts/app/viewmodels/accounts.js"></script>
<script type="text/javascript" src="~/scripts/app/viewmodels/files.js"></script>
<script type="text/javascript" src="~/scripts/app/builderApp.js"></script>
}

Zuilding.Web/Views/investor.cshtml
@{
    Layout = "_layout.cshtml";
}

<!--
     Main content page for Builder
-->
<div data-bind="visible: menu.current() == ''">
    @Html.Partial("/views/investor/_home.cshtml")
</div>

@*<div data-bind="with: checklists, visible: menu.current().name == 'Checklists'">
    @Html.Partial("/views/checklist/_index.cshtml")
</div>*@
<div data-bind="with: proposals, visible: menu.current().name == 'Proposals'">
    @Html.Partial("/Views/proposal/_container.cshtml")
</div>
<div data-bind="with: contacts, visible: menu.current().name == 'Contacts'">
    @Html.Partial("/Views/contact/_index.cshtml")
</div>
<div data-bind="with: accounts, visible: menu.current() == 'Accounts'">
    @Html.Partial("/Views/accounts/_accounts.cshtml")
</div>

@section scripts {
    <script type="text/javascript" src="~/scripts/app/viewmodels/proposal/container.js"></script>
    <script type="text/javascript" src="~/scripts/app/viewmodels/proposal/page.js"></script>
    <script type="text/javascript" src="~/scripts/app/viewmodels/proposal/spec.js"></script>
    <script type="text/javascript" src="~/scripts/app/viewmodels/proposal/financials.js"></script>
    @*<script type="text/javascript" src="~/scripts/app/viewmodels/checklist.js"></script>*@
    <script type="text/javascript" src="~/scripts/app/viewmodels/list.js"></script>
    <script type="text/javascript" src="~/scripts/app/viewmodels/contacts.js"></script>
    <script type="text/javascript" src="~/scripts/app/viewmodels/accounts.js"></script>
    <script type="text/javascript" src="~/scripts/app/investorApp.js"></script>
}

Zuilding.Web/Views/login.cshtml
@model Zuilding.Web.Models.LoginModel
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>Log in</title>
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400' rel='stylesheet' type='text/css'>
    <link href="Content/style.css" rel="stylesheet" type="text/css" media="screen" title="stylesheet" />
    <!-- Scripts -->
    <script type="text/javascript" src="Scripts/js/modernizr.js"></script>
    @Scripts.Render("~/bundles/jquery")


    @*<script type="text/javascript" src="../../../../../ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>*@
    <script type="text/javascript" src="Scripts/js/script.js"></script>
    <!--(if it IE 9) >
    <script>
        document.createElement("article");
        document.createElement("aside");
        document.createElement("footer");
        document.createElement("header");
        document.createElement("nav");
        document.createElement("section");
    </script>
    <! (endif)-->
</head>
<body>
    <!-- Styles -->
    
    <style type="text/css">
        body {
            color: #FFF;
        }
        /* This will change the main site text colour to white */
    </style>

   
    <section id="loginForm">

        <div id="wrapper">
            <header id="site-main">
                <div class="container1">
                    <img src="Content/images/logoBLUE.png" width="184" height="319">
                </div>
            </header><!-- end header -->
            <main>
                <section>
                    <div id="site-middle">
                        <div class="container">
                            <section class="subscribe">
                                <h2>Client Login</h2>
                                <!-- Add your subscription form code here, more details in the documentation  -->
                                <form action="/Authentication/login" method="post" class="php-newsletter">
                                    @Html.AntiForgeryToken()    
                                    <input name="UserName" id="UserName" placeholder="Enter Your Username" class="forminput" />
                                    <input type="Password" name="Password" id="Password" placeholder="******" class="forminput" />
                                    <input type="submit" class="forminput" name="subscribe_submit" id="subscribe_submit" value="Log in" /><br />
                                    <a href="#" class="formlinks"> Forgot Username? </a> |  <a href="#" class="formlinks"> Forgot Password?</a>
                                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" class="form-control" id="RememberMe" name="RememberMe" />Remember Me
                                </form> 
                                <!-- end of subscription form code -->
                            </section>
                        </div>
                    </div><!-- end site main -->
                </section>
            </main>

            <footer id="site-footer">
                <div class="container">
                    <p>
                        &copy; 2014 Built-in 360&nbsp;&nbsp;&nbsp;&middot;&nbsp;&nbsp;&nbsp;
                        <a href="#">Terms and Conditions</a>&nbsp;&nbsp;&nbsp;&middot;&nbsp;&nbsp;&nbsp;
                        <a href="#">Privacy Policy</a>&nbsp;&nbsp;&nbsp;&middot;&nbsp;&nbsp;&nbsp;
                        <a href="#">Contact Us</a>
                    </p>
                </div>
            </footer><!-- end site footer -->
        </div><!-- end wrapper -->

    </section>

</body>
</html>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Zuilding.Web/Views/register.cshtml
@model Zuilding.Web.Models.RegisterModel

@using (Html.BeginForm("Register", "Authentication"))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Register New Builder</h4>
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.UserName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName)
                @Html.ValidationMessageFor(model => model.UserName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password)
                @Html.ValidationMessageFor(model => model.Password)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmPassword)
                @Html.ValidationMessageFor(model => model.ConfirmPassword)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tenantName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tenantName)
                @Html.ValidationMessageFor(model => model.tenantName)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}